2024-02-29 16:18:00,435 INFO    MainThread:22615 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-29 16:18:00,435 INFO    MainThread:22615 [wandb_setup.py:_flush():76] Configure stats pid to 22615
2024-02-29 16:18:00,435 INFO    MainThread:22615 [wandb_setup.py:_flush():76] Loading settings from /home/rafael/.config/wandb/settings
2024-02-29 16:18:00,435 INFO    MainThread:22615 [wandb_setup.py:_flush():76] Loading settings from /home/rafael/Projects/ETH/FS2024/PLR_exercises/plr-exercise/wandb/settings
2024-02-29 16:18:00,435 INFO    MainThread:22615 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-29 16:18:00,435 INFO    MainThread:22615 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-29 16:18:00,435 INFO    MainThread:22615 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'scripts/train_hyperparamtuning.py', 'program_abspath': '/home/rafael/Projects/ETH/FS2024/PLR_exercises/plr-exercise/scripts/train_hyperparamtuning.py', 'program': '/home/rafael/Projects/ETH/FS2024/PLR_exercises/plr-exercise/scripts/train_hyperparamtuning.py'}
2024-02-29 16:18:00,435 INFO    MainThread:22615 [wandb_init.py:_log_setup():526] Logging user logs to /home/rafael/Projects/ETH/FS2024/PLR_exercises/plr-exercise/wandb/run-20240229_161800-grd3cf7w/logs/debug.log
2024-02-29 16:18:00,435 INFO    MainThread:22615 [wandb_init.py:_log_setup():527] Logging internal logs to /home/rafael/Projects/ETH/FS2024/PLR_exercises/plr-exercise/wandb/run-20240229_161800-grd3cf7w/logs/debug-internal.log
2024-02-29 16:18:00,435 INFO    MainThread:22615 [wandb_init.py:init():566] calling init triggers
2024-02-29 16:18:00,435 INFO    MainThread:22615 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-02-29 16:18:00,436 INFO    MainThread:22615 [wandb_init.py:init():616] starting backend
2024-02-29 16:18:00,436 INFO    MainThread:22615 [wandb_init.py:init():620] setting up manager
2024-02-29 16:18:00,439 INFO    MainThread:22615 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-02-29 16:18:00,440 INFO    MainThread:22615 [wandb_init.py:init():628] backend started and connected
2024-02-29 16:18:00,446 INFO    MainThread:22615 [wandb_init.py:init():720] updated telemetry
2024-02-29 16:18:00,454 INFO    MainThread:22615 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-29 16:18:00,895 ERROR   MainThread:22615 [wandb_init.py:init():779] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-02-29 16:18:00,966 ERROR   MainThread:22615 [wandb_init.py:init():1194] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/home/rafael/venv/plr_env/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/home/rafael/venv/plr_env/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-02-29 16:18:01,968 WARNING MsgRouterThr:22615 [router.py:message_loop():77] message_loop has been closed
